import type { TreeNode } from "@/components/TreeMultiSelect";

function districtChildren(
  provinceLabel: string,
  districts: string[],
): TreeNode[] {
  return [
    {
      id: `${provinceLabel}-all`,
      label: `${provinceLabel} 전체`,
      value: provinceLabel,
    },
    ...districts.map((district) => ({
      id: `${provinceLabel}-${district}`,
      label: district,
      value: `${provinceLabel} ${district}`,
    })),
  ];
}

function provinceBranch(
  id: string,
  label: string,
  districts: string[],
): TreeNode {
  return {
    id,
    label,
    children: districtChildren(label, districts),
  };
}

/** 활동구역 트리 (회원가입) */
export const REGION_TREE: TreeNode[] = [
  { id: "national", label: "전국", value: "전국" },
  provinceBranch("seoul", "서울", [
    "강남",
    "강동",
    "강북",
    "강서",
    "관악",
    "광진",
    "구로",
    "금천",
    "노원",
    "도봉",
    "동대문",
    "동작",
    "마포",
    "서대문",
    "서초",
    "성동",
    "성북",
    "송파",
    "양천",
    "영등포",
    "용산",
    "은평",
    "종로",
    "중구",
    "중랑",
  ]),
  provinceBranch("gyeonggi", "경기", [
    "수원",
    "성남",
    "고양",
    "용인",
    "부천",
    "안산",
    "안양",
    "남양주",
    "화성",
    "평택",
    "의정부",
    "시흥",
    "파주",
    "김포",
    "광명",
    "광주",
    "군포",
    "하남",
    "오산",
    "이천",
    "안성",
    "구리",
    "포천",
    "양주",
    "여주",
    "연천",
    "가평",
    "양평",
    "동두천",
    "과천",
    "의왕",
  ]),
  provinceBranch("incheon", "인천", [
    "중구",
    "동구",
    "미추홀",
    "연수",
    "남동",
    "부평",
    "계양",
    "서구",
    "강화",
    "옹진",
  ]),
  {
    id: "other",
    label: "그 외 지역",
    children: [
      provinceBranch("busan", "부산", [
        "중구",
        "서구",
        "동구",
        "영도",
        "부산진",
        "동래",
        "남구",
        "북구",
        "해운대",
        "사하",
        "금정",
        "강서",
        "연제",
        "수영",
        "사상",
        "기장",
      ]),
      provinceBranch("daegu", "대구", [
        "중구",
        "동구",
        "서구",
        "남구",
        "북구",
        "수성",
        "달서",
        "달성",
        "군위",
      ]),
      provinceBranch("gwangju", "광주", ["동구", "서구", "남구", "북구", "광산"]),
      provinceBranch("daejeon", "대전", ["동구", "중구", "서구", "유성", "대덕"]),
      provinceBranch("ulsan", "울산", ["중구", "남구", "동구", "북구", "울주"]),
      provinceBranch("sejong", "세종", ["세종"]),
      provinceBranch("gangwon", "강원", [
        "춘천",
        "원주",
        "강릉",
        "동해",
        "태백",
        "속초",
        "삼척",
        "홍천",
        "횡성",
        "영월",
        "평창",
        "정선",
        "철원",
        "화천",
        "양구",
        "인제",
        "고성",
        "양양",
      ]),
      provinceBranch("chungbuk", "충북", [
        "청주",
        "충주",
        "제천",
        "보은",
        "옥천",
        "영동",
        "증평",
        "진천",
        "괴산",
        "음성",
        "단양",
      ]),
      provinceBranch("chungnam", "충남", [
        "천안",
        "공주",
        "보령",
        "아산",
        "서산",
        "논산",
        "계룡",
        "당진",
        "금산",
        "부여",
        "서천",
        "청양",
        "홍성",
        "예산",
        "태안",
      ]),
      provinceBranch("jeonbuk", "전북", [
        "전주",
        "군산",
        "익산",
        "정읍",
        "남원",
        "김제",
        "완주",
        "진안",
        "무주",
        "장수",
        "임실",
        "순창",
        "고창",
        "부안",
      ]),
      provinceBranch("jeonnam", "전남", [
        "목포",
        "여수",
        "순천",
        "나주",
        "광양",
        "담양",
        "곡성",
        "구례",
        "고흥",
        "보성",
        "화순",
        "장흥",
        "강진",
        "해남",
        "영암",
        "무안",
        "함평",
        "영광",
        "장성",
        "완도",
        "진도",
        "신안",
      ]),
      provinceBranch("gyeongbuk", "경북", [
        "포항",
        "경주",
        "김천",
        "안동",
        "구미",
        "영주",
        "영천",
        "상주",
        "문경",
        "경산",
        "의성",
        "청송",
        "영양",
        "영덕",
        "청도",
        "고령",
        "성주",
        "칠곡",
        "예천",
        "봉화",
        "울진",
        "울릉",
      ]),
      provinceBranch("gyeongnam", "경남", [
        "창원",
        "진주",
        "통영",
        "사천",
        "김해",
        "밀양",
        "거제",
        "양산",
        "의령",
        "함안",
        "창녕",
        "고성",
        "남해",
        "하동",
        "산청",
        "함양",
        "거창",
        "합천",
      ]),
      provinceBranch("jeju", "제주", ["제주", "서귀포"]),
    ],
  },
];

/** 체육관 활동 지역 (전국 제외, 회원가입과 동일 트리) */
export const GYM_REGION_TREE: TreeNode[] = REGION_TREE.filter(
  (node) => node.value !== "전국",
);
