create table if not exists public.user_consent_records (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  terms_version text not null,
  privacy_version text not null,
  terms_agreed boolean not null default true,
  privacy_agreed boolean not null default true,
  marketing_agreed boolean not null default false,
  source text not null default 'onboarding_social',
  created_at timestamptz not null default now(),
  constraint user_consent_records_terms_agreed_check check (terms_agreed = true),
  constraint user_consent_records_privacy_agreed_check check (privacy_agreed = true),
  constraint user_consent_records_source_check check (
    source in ('signup_email', 'onboarding_social', 'reauthorization', 'settings')
  ),
  constraint user_consent_records_terms_version_check check (length(trim(terms_version)) > 0),
  constraint user_consent_records_privacy_version_check check (length(trim(privacy_version)) > 0)
);

create index if not exists user_consent_records_user_created_idx
  on public.user_consent_records (user_id, created_at desc);

alter table public.user_consent_records enable row level security;

drop policy if exists "Users can read own consent records" on public.user_consent_records;
create policy "Users can read own consent records"
  on public.user_consent_records
  for select
  to authenticated
  using (auth.uid() = user_id);

drop policy if exists "Users can create own consent records" on public.user_consent_records;
create policy "Users can create own consent records"
  on public.user_consent_records
  for insert
  to authenticated
  with check (auth.uid() = user_id);

revoke update, delete on table public.user_consent_records from authenticated;
grant select, insert on table public.user_consent_records to authenticated;
grant all on table public.user_consent_records to service_role;
grant usage, select on sequence public.user_consent_records_id_seq to authenticated, service_role;
